import {
  apiSlice,
  appSlice,
  auditSlice,
  bearerSlice,
  bulletinSlice,
  challengeSlice,
  contactSlice,
  credentialSlice,
  handleSlice,
  historySlice,
  keySlice,
  localeSlice,
  logSlice,
  otpSlice,
  profileSlice,
  roleSlice,
  serviceSlice,
  sessionSlice,
  systemSlice,
  userSlice,
  noteSlice,
} from './data/index.js';

export const stateReducers = {
  [apiSlice.name]: apiSlice.reducer,
  [appSlice.name]: appSlice.reducer,
  [auditSlice.name]: auditSlice.reducer,
  [bearerSlice.name]: bearerSlice.reducer,
  [bulletinSlice.name]: bulletinSlice.reducer,
  [challengeSlice.name]: challengeSlice.reducer,
  [contactSlice.name]: contactSlice.reducer,
  [credentialSlice.name]: credentialSlice.reducer,
  [handleSlice.name]: handleSlice.reducer,
  [keySlice.name]: keySlice.reducer,
  [historySlice.name]: historySlice.reducer,
  [localeSlice.name]: localeSlice.reducer,
  [logSlice.name]: logSlice.reducer,
  [noteSlice.name]: noteSlice.reducer,
  [otpSlice.name]: otpSlice.reducer,
  [profileSlice.name]: profileSlice.reducer,
  [roleSlice.name]: roleSlice.reducer,
  [serviceSlice.name]: serviceSlice.reducer,
  [sessionSlice.name]: sessionSlice.reducer,
  [systemSlice.name]: systemSlice.reducer,
  [userSlice.name]: userSlice.reducer,
};

export default stateReducers;
