name: Integrity Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:

  audit:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Audit Packages
        run: pnpm audit --audit-level moderate

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Update
        run: sudo apt update

      - name: Install ffmpeg
        run: sudo apt install ffmpeg

      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup NodeJS with PNPM Caching
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install NodeJS Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: |
          pnpm build:libs
          pnpm build

      - name: Lint for Code-Style Errors
        run: |
          pnpm lint:libs
          pnpm lint

      - name: Run Unit Tests
        run: |
          pnpm test:libs
          pnpm test
