name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  integrity-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./github/workflows/integrity-check.yml

  release:
    runs-on: ubuntu-latest
    needs: integrity-check
    steps:
    - uses: google-github-actions/release-please-action@v3
      id: release
      with:
        release-type: node
        command: manifest
        token: ${{ secrets.GITHUB_TOKEN }}
        default-branch: main

    - name: Publish
      uses: ./.github/workflows/publish.yml
      if: ${{ steps.release.outputs.release_created }}